# Generated by Django 4.0.5 on 2022-06-12 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='senha',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
    ]
