# Generated by Django 4.0.5 on 2022-06-12 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluguel',
            name='status',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
