# Generated by Django 4.0.5 on 2022-06-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0002_aluguel_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluguel',
            name='localRetirada',
        ),
        migrations.AddField(
            model_name='aluguel',
            name='idFornecedor',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
