# Generated by Django 4.0.5 on 2022-06-12 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=100)),
                ('pathImagem', models.CharField(max_length=1000)),
                ('grupo', models.CharField(max_length=20)),
                ('tamanhoMala', models.CharField(max_length=1)),
                ('abs', models.BooleanField()),
                ('airbag', models.BooleanField()),
                ('vidroEletrico', models.BooleanField()),
                ('arcondicionado', models.BooleanField()),
                ('travaEletrica', models.BooleanField()),
                ('direcaoHidraulica', models.BooleanField()),
                ('automatico', models.BooleanField()),
                ('tetoSolar', models.BooleanField()),
                ('portas', models.IntegerField()),
                ('malas', models.IntegerField()),
                ('assentos', models.IntegerField()),
                ('motor', models.FloatField()),
            ],
        ),
    ]
