# Generated by Django 4.0.5 on 2022-06-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0003_alter_carro_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carro',
            name='marca',
        ),
        migrations.AddField(
            model_name='carro',
            name='cor',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carro',
            name='idMarca',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carro',
            name='valor',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
