# Generated by Django 4.0.5 on 2022-06-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0004_remove_carro_marca_carro_cor_carro_idmarca_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carro',
            name='idMarca',
        ),
        migrations.AddField(
            model_name='carro',
            name='marca',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
