# Generated by Django 4.0.5 on 2022-06-15 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0005_remove_carro_idmarca_carro_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='fornecedor',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
